name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "5.4"

      - uses: leafo/gh-actions-luarocks@v4

      - name: setup
        run: |
          luarocks install luacheck

      - name: lint
        run: |
          make lint
