name: Luacheck

on: [ push, pull_request ]

jobs:

  luacheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Luacheck
        uses: lunarmodules/luacheck@2445a9dd3859655646bd6eb848459f2b46b4a3e3 # v0
