name: Test

on: [ push, pull_request ]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.4", "5.3", "5.2", "5.1", "luajit" ] # , "luajit-openresty" ]
        debug: ["", "_G.debug = nil"] # also run with debug lib disabled
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@d84e7d61946edb679210088bc1378c099fde51fe # v9
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4

      - name: Setup dependencies
        run: |
          luarocks install luasocket


      - name: Run regression tests
        run: make test
        env:
          LUA_INIT: ${{ matrix.debug }}
